/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/layouts/AppLayout.vue')['default']
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    BaseInconeSvg: typeof import('./src/components/base/BaseInconeSvg.vue')['default']
    DarkMode: typeof import('./src/components/base/DarkMode.vue')['default']
    DarkModeHidden: typeof import('./src/components/base/DarkModeHidden.vue')['default']
    DarkModeSwitcher: typeof import('./src/components/base/DarkModeSwitcher.vue')['default']
    HeaderNav: typeof import('./src/components/common/HeaderNav.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeBanner: typeof import('./src/components/common/HomeBanner.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LangSwitcher: typeof import('./src/components/common/LangSwitcher.vue')['default']
    LoadingAnimation: typeof import('./src/components/base/LoadingAnimation.vue')['default']
    PageFooter: typeof import('./src/components/common/PageFooter.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
